# Generated by Django 6.0.4 on 2026-04-21 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(choices=[('admission', 'Admission'), ('formation', 'Formation'), ('recherche', 'Recherche'), ('partenariat', 'Partenariat'), ('autre', 'Autre')], default='autre', max_length=30, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_handled', models.BooleanField(default=False, verbose_name='Traité')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'ordering': ['key'], 'verbose_name': 'Paramètre du site', 'verbose_name_plural': 'Paramètres du site'},
        ),
        migrations.AddField(
            model_name='news',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Résumé court affiché sur les listes (généré automatiquement si vide)', max_length=300, verbose_name='Extrait'),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='slider',
            name='link_icon',
            field=models.CharField(blank=True, default='fas fa-arrow-right', max_length=50, verbose_name='Icône du lien (classe Font Awesome)'),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='campusfeature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campus/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='campusfeature',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='campusfeature',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accueil.program', verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=20, verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accueil.faculty', verbose_name='Faculté'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(max_length=220),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faculties/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(choices=[('about', 'À propos'), ('mission', 'Mission'), ('history', 'Histoire'), ('governance', 'Gouvernance'), ('accreditation', 'Accréditation'), ('mot_directeur', 'Mot du Directeur'), ('perspectives', 'Perspectives'), ('psd', 'PSD 2022-2025')], max_length=30, unique=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='program',
            name='credits',
            field=models.IntegerField(default=0, verbose_name='Crédits ECTS'),
        ),
        migrations.AlterField(
            model_name='program',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='accueil.department', verbose_name='Département'),
        ),
        migrations.AlterField(
            model_name='program',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=200, verbose_name='Journal/Revue'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='accueil.researchlab', verbose_name='Laboratoire'),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='research/labs/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='slug',
            field=models.SlugField(max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='researchlab',
            name='website',
            field=models.URLField(blank=True, verbose_name='Site web'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Clé'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='value',
            field=models.TextField(verbose_name='Valeur'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Sous-titre'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date', 'is_published'], name='accueil_eve_start_d_823456_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['name'], name='accueil_fac_name_8bfe7c_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-published_at', 'is_published'], name='accueil_new_publish_1ef724_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category'], name='accueil_new_categor_187a75_idx'),
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['degree_type', 'is_active'], name='accueil_pro_degree__dc9375_idx'),
        ),
        migrations.AddIndex(
            model_name='publication',
            index=models.Index(fields=['-year'], name='accueil_pub_year_94f669_idx'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('program', 'code'), name='unique_course_code_per_program'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('faculty', 'slug'), name='unique_department_slug_per_faculty'),
        ),
    ]
