from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("institution/mot-directeur/", views.mot_directeur, name="mot_directeur"),
    path("institution/perspectives/", views.perspectives, name="perspectives"),
    path("institution/psd-2022-2025/", views.psd_2022_2025, name="psd_2022_2025"),
    path("faculties/", views.faculties, name="faculties"),
    path("faculties/<slug:slug>/", views.faculty_detail, name="faculty_detail"),
    path("programs/", views.programs, name="programs"),
    path("programs/<slug:slug>/", views.program_detail, name="program_detail"),
    path("formations/resultats/", views.resultats_academiques, name="resultats_academiques"),
    path("campus/", views.campus, name="campus"),
    path("admissions/", views.admissions, name="admissions"),
    path("admissions/<slug:slug>/", views.admissions_detail, name="admissions_detail"),
    path("about/", views.about, name="about"),
    path("research/", views.research, name="research"),
    path("research/<slug:slug>/", views.lab_detail, name="lab_detail"),
    path("publications/", views.publications, name="publications"),
    path("news/", views.news, name="news"),
    path("news/<slug:slug>/", views.news_detail, name="news_detail"),
    path("events/", views.events, name="events"),
    path("events/<slug:slug>/", views.event_detail, name="event_detail"),
    path("partners/", views.partners, name="partners"),
    path("contact/", views.contact, name="contact"),
    path("search/", views.search, name="search"),
    path("mediatheque/", views.mediatheque, name="mediatheque"),
    path("faq/", views.faq, name="faq"),
    path("vie-campus/", views.vie_campus, name="vie_campus"),
    path("etudiants/scolarite/", views.scolarite, name="scolarite"),
    path("etudiants/stages/", views.stages, name="stages"),
    path("etudiants/bibliotheque/", views.bibliotheque, name="bibliotheque"),
    path("etudiants/vie-associative/", views.vie_associative, name="vie_associative"),
    path("mentions-legales/", views.mentions_legales, name="mentions_legales"),
    path("politique-confidentialite/", views.politique_confidentialite, name="politique_confidentialite"),
    path("plan-du-site/", views.plan_du_site, name="plan_du_site"),
    path("fs-menum/", views.fs_menum, name="fs_menum"),
    path("corps-enseignant/", views.corps_enseignant, name="corps_enseignant"),
]
